# Generated by Django 5.2.4 on 2025-07-25 09:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleSearchResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=1000)),
                ('snippet', models.TextField(blank=True, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=2)),
                ('search_query', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_text', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('search_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='articles.articlesearchresult')),
            ],
        ),
    ]
